import { Item } from '../../types';

const items: Item[] = [
  {
    id: 1,
    type: 'drink',
    name: 'Americano',
    cost: 2,
    countPerWeek: 128,
    rating: 4.8,
    calories: 0,
    img: 'americano.jpg',
    weght: 50,
    tags: ['<2'],
    startSell: Date.now(),
  },
  {
    id: 2,
    type: 'food',
    name: 'BBQ-Hamburger',
    cost: 4.2,
    countPerWeek: 22,
    rating: 3.8,
    calories: 300,
    img: 'bbq-hamburger.jpg',
    weght: 320,
    tags: ['<5', 'delivery', 'changing reception'],
    startSell: Date.now(),
  },
  {
    id: 3,
    type: 'food',
    name: 'BBQ-Shawarma',
    cost: 7.3,
    countPerWeek: 20,
    rating: 4.3,
    calories: 500,
    img: 'bbq-shawarma.jpg',
    weght: 600,
    tags: ['<5', 'delivery', 'changing reception'],
    startSell: Date.now(),
  },
  {
    id: 4,
    type: 'food',
    name: 'Cappuccino',
    cost: 2.6,
    countPerWeek: 254,
    rating: 4.6,
    calories: 160,
    img: 'cappuccino.jpg',
    weght: 300,
    tags: ['<2'],
    startSell: Date.now(),
  },
  {
    id: 5,
    type: 'drink',
    name: 'Cherry-Lime Tea',
    cost: 2,
    countPerWeek: 142,
    rating: 4.8,
    calories: 10,
    img: 'cherry-lime-tea.jpg',
    weght: 250,
    tags: ['<2'],
    startSell: Date.now(),
  },
  {
    id: 6,
    type: 'food',
    name: 'Chicken Shawarma',
    cost: 7.5,
    countPerWeek: 85,
    rating: 4.2,
    calories: 500,
    img: 'chicken-shawarma.jpg',
    weght: 600,
    tags: ['<5', 'delivery', 'changing reception'],
    startSell: Date.now(),
  },
  {
    id: 7,
    type: 'food',
    name: 'French Hot-Dog',
    cost: 4.2,
    countPerWeek: 36,
    rating: 2.8,
    calories: 250,
    img: 'french-hot-dog.jpg',
    weght: 180,
    tags: ['<2', 'delivery'],
    startSell: Date.now(),
  },
  {
    id: 8,
    type: 'food',
    name: 'Hamburger',
    cost: 5.8,
    countPerWeek: 94,
    rating: 4.3,
    calories: 250,
    img: 'hamburger.jpg',
    weght: 400,
    tags: ['<5', 'delivery', 'changing reception'],
    startSell: Date.now(),
  },
  {
    id: 9,
    type: 'food',
    name: 'Hot-Dog',
    cost: 4.6,
    countPerWeek: 75,
    rating: 4.1,
    calories: 300,
    img: 'hot-dog.jpg',
    weght: 300,
    tags: ['<2', 'delivery'],
    startSell: Date.now(),
  },
  {
    id: 10,
    type: 'food',
    name: 'King-Hamburger',
    cost: 7.2,
    countPerWeek: 92,
    rating: 4.9,
    calories: 630,
    img: 'king-hamburger.jpg',
    weght: 600,
    tags: ['<5', 'delivery', 'changing reception'],
    startSell: Date.now(),
  },
  {
    id: 11,
    type: 'food',
    name: 'King-Hawarma',
    cost: 8.6,
    countPerWeek: 76,
    rating: 4.0,
    calories: 800,
    img: 'king-hamburger.jpg',
    weght: 800,
    tags: ['<5', 'delivery', 'changing reception'],
    startSell: Date.now(),
  },
  {
    id: 12,
    type: 'drink',
    name: 'Latte',
    cost: 2.6,
    countPerWeek: 274,
    rating: 4.5,
    calories: 190,
    img: 'latte.jpg',
    weght: 300,
    tags: ['<2'],
    startSell: Date.now(),
  },
  {
    id: 13,
    type: 'drink',
    name: 'Raspbery Tea',
    cost: 2,
    countPerWeek: 95,
    rating: 4.8,
    calories: 10,
    img: 'raspbery-tea.jpg',
    weght: 250,
    tags: ['<2'],
    startSell: Date.now(),
  },
  {
    id: 14,
    type: 'drink',
    name: 'Seabuckthorn Tea',
    cost: 2,
    countPerWeek: 123,
    rating: 4.3,
    calories: 10,
    img: 'seabuckthorn-tea.jpg',
    weght: 250,
    tags: ['<2'],
    startSell: Date.now(),
  },
  {
    id: 15,
    type: 'food',
    name: 'Fries',
    cost: 3.6,
    countPerWeek: 84,
    rating: 3.8,
    calories: 320,
    img: 'fries.jpg',
    weght: 300,
    tags: ['<5', 'delivery'],
    startSell: Date.now(),
  },
];

export default items;
